### ISSUE TITLE
Add debugging options

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/aws-s3-download#1]
The following debugging options should be added 

1. `maxConcurrency`
2. `maxPendingConnectionAcquires`  
3. `maxConnection` 
4. enable wire logging for the SDK

Those settings should be provided either via env vars or java system properties

### References 

* https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html#setting-maximum-connections
* https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setMaxConnections-int-
* https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-logging.html

**Comment by jordeu** [comment]
It seems that `maxConcurrency` and `maxPendingConnectionAcquires` are SDK v2 properties and I didn't find the SDK v1 equivalent. Also we are importing SDK v2 but it seems that we are only using SDK v1 here.

What do we want to do; update to use SDK v2 or just implement the available debug options at v1 (`maxConnection` & `wire logging`) ?

**Comment by pditommaso** [comment]
Interesting, this makes me think the AWS support assumed we/they are using SDK v2. I think it's worth adding a similar implementation using SDK v2. 

That's what was trying to do with this class that a complete example I've found on Amazon resources, However I didn't manage to make it work 

https://github.com/seqeralabs/aws-s3-download/blob/master/src/main/java/XferMgrDownload.java


Maybe it can be removed all non-essential logic and just make it similar to https://github.com/seqeralabs/aws-s3-download/blob/master/src/main/java/Main1.java

**Comment by jordeu** [comment]
When using SDK v2 `TransferManager` it is only possible to set `maxConcurreny` because it is not yet possible to set an `S3AsyncClient` (see https://github.com/aws/aws-sdk-java-v2/issues/2896).
